In [1]:
#Implementing Numpy Concepts
import numpy
numpy.__version__

'2.3.5'

In [4]:
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [6]:
import numpy as np
a = np.zeros((2,2))   #create an array of all zeros
print(a)              #prints "[[0. 0.]]"

b = np.ones((1,2))
print(b)

c = np.full((2,2),7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.77111032 0.79272961]
 [0.99573983 0.50477386]]


In [7]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [8]:
import numpy as np
arr = np.array([1.1,2.2,3.3])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [9]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print('shape of array :' ,arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [10]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [15]:
from numpy import random
x=random.randint(100,size=(5))
print(x)

[68 81  0 18 42]
